Repository KaizeNodeLabs/starkiro, pull requests merged in 2024-12, with the labels that each got.

#55 docs: fill guidelines into dedicated files
  docs/CONTRIBUTION_GUIDELINES.md
  docs/GIT_GUIDELINES.md
  docs/ISSUES_GUIDELINES.md
Labels: documentation, actual: 1

#57 Remove the files .tools-version and docs.md
  .tool-versions
  docs/docs.md
Labels: actual: 1

#73 Fix template not rendering for issues and PRs
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation, actual: 1, ODHack11

#74 docs: Add Cargo installation steps to README for scripts and contracts
  README.md
Labels: ODHack11

#76 Add check .toolsversion to README.d
  README.md
Labels: documentation, actual: 2, ODHack11

#75 created even_or_odd.md file Documentation in even_or_odd folder > src…
  cairo/scripts/even_or_odd/src/even_or_odd.md
Labels: documentation, actual: 2, ODHack11

#81 Fix: simple counter contract
  starknet/contracts/simple_counter/Scarb.toml
  starknet/contracts/simple_counter/tests/test_simple_counter.cairo
Labels: bug, actual: 1, ODHack11

#77 [docs]: Create a Deployment_Guide.md
  docs/DEPLOYMENT_GUIDE.md
Labels: documentation, actual: 1, ODHack11

#79 complete feat/stack_data_structure
  cairo/scripts/stack_data_structure/.gitignore
  cairo/scripts/stack_data_structure/.snfoundry_cache/.prev_tests_failed
  cairo/scripts/stack_data_structure/.tool-versions
  cairo/scripts/stack_data_structure/Scarb.lock
  cairo/scripts/stack_data_structure/Scarb.toml
  cairo/scripts/stack_data_structure/src/lib.cairo
  cairo/scripts/stack_data_structure/src/stack_data_structure.cairo
  cairo/scripts/stack_data_structure/src/stack_data_structure_test.cairo
  starknet/contracts/simple_counter/Scarb.lock
Labels: actual: 2, ODHack11

#78 Issue #59: Implement script/contract for random number generator
  starknet/contracts/random_number_generator/.gitignore
  starknet/contracts/random_number_generator/.tool-versions
  starknet/contracts/random_number_generator/Scarb.lock
  starknet/contracts/random_number_generator/Scarb.toml
  starknet/contracts/random_number_generator/snfoundry.toml
  starknet/contracts/random_number_generator/src/RandomNumberGeneratorContract.cairo
  starknet/contracts/random_number_generator/src/lib.cairo
  starknet/contracts/random_number_generator/tests/test_contract.cairo
Labels: actual: 2, ODHack11

#80 Doc: Add READNE for counter_access_control_contract
  starknet/contracts/counter_access_control/README.md
Labels: documentation, actual: 1, ODHack11

#83 Implement a simple Crowdfunding contract example
  starknet/contracts/crowdfounding/.gitignore
  starknet/contracts/crowdfounding/Scarb.lock
  starknet/contracts/crowdfounding/Scarb.toml
  starknet/contracts/crowdfounding/src/crowdfunding.cairo
  starknet/contracts/crowdfounding/src/lib.cairo
  starknet/contracts/crowdfounding/tests/test_crowdfounding.cairo
Labels: actual: 2, ODHack11
