Repository KaizeNodeLabs/starkiro, pull requests merged in 2025-01, with the labels that each got.

#89 Feat: added power function of a number
  cairo/scripts/simple_math/src/simple_math.cairo
Labels: actual: 1

#92 Even or odd doc
  cairo/scripts/even_or_odd/even_or_odd.md
  cairo/scripts/even_or_odd/src/even_or_odd.cairo
Labels: actual: 1

#117 feat: implement prime checker function
  cairo/scripts/is_prime/.gitignore
  cairo/scripts/is_prime/.tool-versions
  cairo/scripts/is_prime/Scarb.lock
  cairo/scripts/is_prime/Scarb.toml
  cairo/scripts/is_prime/src/is_prime.cairo
  cairo/scripts/is_prime/src/lib.cairo
Labels: ODBoost

#122 [FEAT] Add GHA to run `scarb build` for contracts and scripts
  .github/workflows/build_programs.yml
  build_programs.sh
Labels: ODBoost

#114 feat: Add GHA to run snforge test for contracts
  .github/workflows/snforge-test.yml
Labels: ODBoost

#115 Feat: create an address validator
  cairo/scripts/address_validator/.gitignore
  cairo/scripts/address_validator/.tool-versions
  cairo/scripts/address_validator/Scarb.lock
  cairo/scripts/address_validator/Scarb.toml
  cairo/scripts/address_validator/src/address_validator.cairo
  cairo/scripts/address_validator/src/lib.cairo
Labels: ODBoost

#121 feat: create binary search script
  cairo/scripts/binary_search/.gitignore
  cairo/scripts/binary_search/.tool-versions
  cairo/scripts/binary_search/Scarb.lock
  cairo/scripts/binary_search/Scarb.toml
  cairo/scripts/binary_search/src/binary_search.cairo
  cairo/scripts/binary_search/src/lib.cairo
Labels: ODBoost

#116 [FEAT]: Implement an array sorting script
  cairo/scripts/sorting/.gitignore
  cairo/scripts/sorting/.tool-versions
  cairo/scripts/sorting/Scarb.lock
  cairo/scripts/sorting/Scarb.toml
  cairo/scripts/sorting/snfoundry.toml
  cairo/scripts/sorting/src/bubble_sort.cairo
  cairo/scripts/sorting/src/interface.cairo
  cairo/scripts/sorting/src/lib.cairo
  cairo/scripts/sorting/src/merge_sort.cairo
  cairo/scripts/sorting/src/quick_sort.cairo
  cairo/scripts/sorting/tests/test_bubble_sort.cairo
  cairo/scripts/sorting/tests/test_merge_sort.cairo
  cairo/scripts/sorting/tests/test_quick_sort.cairo
Labels: ODBoost

#111 Adding escrow with multiple recipients implementation
  starknet/contracts/escrow_multiple_recipients/.gitignore
  starknet/contracts/escrow_multiple_recipients/.tool-versions
  starknet/contracts/escrow_multiple_recipients/Scarb.lock
  starknet/contracts/escrow_multiple_recipients/Scarb.toml
  starknet/contracts/escrow_multiple_recipients/src/escrow.cairo
  starknet/contracts/escrow_multiple_recipients/src/lib.cairo
  starknet/contracts/escrow_multiple_recipients/tests/lib.cairo
  starknet/contracts/escrow_multiple_recipients/tests/test_escrow.cairo
Labels: ODBoost

#119 add vesting contract
  starknet/contracts/token_vesting/.gitignore
  starknet/contracts/token_vesting/.tool-versions
  starknet/contracts/token_vesting/Scarb.lock
  starknet/contracts/token_vesting/Scarb.toml
  starknet/contracts/token_vesting/snfoundry.toml
  starknet/contracts/token_vesting/src/lib.cairo
  starknet/contracts/token_vesting/src/mocks.cairo
  starknet/contracts/token_vesting/src/mocks/free_erc20.cairo
  starknet/contracts/token_vesting/src/vesting.cairo
  starknet/contracts/token_vesting/tests/utils.cairo
  starknet/contracts/token_vesting/tests/vesting.cairo
  starknet/contracts/token_vesting/tests/vesting/test_admin.cairo
  starknet/contracts/token_vesting/tests/vesting/test_vesting.cairo
Labels: ODBoost

#130 Add new cli and dev suit install script
  cli/README.md
  cli/install_dev_suit.sh
Labels: internal contribution

#118 Add staking contract
  starknet/contracts/staking/.gitignore
  starknet/contracts/staking/.tool-versions
  starknet/contracts/staking/Scarb.lock
  starknet/contracts/staking/Scarb.toml
  starknet/contracts/staking/snfoundry.toml
  starknet/contracts/staking/src/Staking.cairo
  starknet/contracts/staking/src/interfaces.cairo
  starknet/contracts/staking/src/interfaces/ierc20.cairo
  starknet/contracts/staking/src/interfaces/istaking.cairo
  starknet/contracts/staking/src/lib.cairo
  starknet/contracts/staking/src/mocks.cairo
  starknet/contracts/staking/src/mocks/mock_reward_token.cairo
  starknet/contracts/staking/src/mocks/mock_staking_token.cairo
  starknet/contracts/staking/tests/test_contract.cairo
  starknet/contracts/staking/tests/test_staking_rewards.cairo
Labels: ODBoost

#132 Fixes #102 - Adding ownable component
  starknet/modules/ownable_component/.gitignore
  starknet/modules/ownable_component/Scarb.lock
  starknet/modules/ownable_component/Scarb.toml
  starknet/modules/ownable_component/snfoundry.toml
  starknet/modules/ownable_component/src/ownable_component.cairo
Labels: ODBoost
